version: '3'

# Define services
services:

  # PostgreSQL Database
  trender-postgres:
    image: "postgres:9.6-alpine"
    container_name: trender-postgres
    volumes:
      - trender-data:/ProgramFiles/PostgreSQL/12/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=trender
      - POSTGRES_USER=trendz
      - POSTGRES_PASSWORD=1234567

  # Spring Boot Backend
  trender-backend:
    build: ./TrenderBackend
    container_name: trender-backend

    environment:
      - DB_SERVER=trender-postgres
      - POSTGRES_DB=trender
      - POSTGRES_USER=trendz
      - POSTGRES_PASSWORD=1234567
    ports:
      - 8081:8081
    links:
      - trender-postgres

  # React Frontend
  trender-frontend:
    build: ./TrenderFrontend
    container_name: trender-frontend

    ports:
      - 3000:80
    links:
      - trender-backend

# Volumes for DB data
volumes:
  trender-data: