version: 2 # use CircleCI 2.0 #
jobs: # a collection of steps
  build_dir: trender-service

  docker: # run the steps with Docker
  — image: circleci/openjdk:8-jdk-stretch # …with this image as the primary container; this is where all `steps` will run

  steps: # a collection of executable commands
  — run: ./mvnw clean install # mvn clean install tells Maven to do the clean phase in each module before running the install phase for each module.